### ISSUE TITLE
Python - subscribe_email is gone in 0.35.0

### ISSUE THREAD

**Issue by lkoniecz** [awslabs/aws-cdk#2983]
**Note: for support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/ask?tags=aws-cdk)**. This repository's issues are intended for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] :beetle: bug report
  - [ ] :rocket: feature request
  - [x] :books: construct library gap
  - [ ] :phone: security issue or vulnerability => Please see [policy](https://github.com/awslabs/aws-cdk/security/policy)
  - [ ] :question: support request => Please see note at the top of this template.

* **What is the current behavior?**
AttributeError: 'Topic' object has no attribute 'subscribe_email'

* **What is the expected behavior (or behavior of feature suggested)?**
Email subscription added to sns

* **What is the motivation / use case for changing the behavior or adding this feature?**
Make the 0.34 CDK complianant code work

* **Please tell us about your environment:**
  
  - CDK CLI Version: 0.35.0 (build c5e43e2)
  - Module Version: 0.35.0
  - OS: Ubuntu 19.4
  - Language: Python

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, gitter, etc)

```
        eks_sns = aws_sns.Topic(scope=self, id='EksSns', display_name='EksSns')
        eks_sns.subscribe_email(name=subscriber, email_address='test@test.com)
```

Used to work in 0.34.0 I can see both from the source code and documentation that the functionality is gone. Unless 0.35.0 is a major release, the change breaks the statement (more on here: https://docs.aws.amazon.com/cdk/latest/guide/aws_construct_lib.html)
```
Versioning
The AWS CDK follows the semantic versioning model. This means that breaking changes are limited to major releases, such as 2.0.

Minor releases, such as 2.4, guarantee that any code written in a previous minor version, such as 2.1, will build, run, and produce the exact same results when built, run, and producing results, as before.
```

**Comment by jogold** [comment]
https://github.com/awslabs/aws-cdk/blob/v0.35.0/CHANGELOG.md#breaking-changes

**sns**: using a queue, lambda, email, URL as SNS Subscriber now requires an integration object from the @aws-cdk/aws-sns-subscribers package.

```
eks_sns.add_subscription(...)
```

**Comment by lkoniecz** [comment]
@jogold

**Comment by jogold** [comment]
https://semver.org/#spec-item-4

**Comment by lkoniecz** [comment]
Thanks for the explanation. Seems like current releases fall into: 
`Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.`

which explains lack of the backward compability.
